### ISSUE TITLE
Multiline comments generation issue

### ISSUE THREAD

**Issue by vadimi** [RicoSuter/NJsonSchema#1462] opened 2021-12-13 15:46 UTC
Hello, after PR #1346 code generation for multiline comments produces invalid `<summary>` xml doc.

For example:

```yaml
    TestType:
      type: object
      properties:
        code:
          type: string
          description: |
            * test1
            * test2
```

produces the following c# code:

```csharp
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.15.3.0 (NJsonSchema v10.6.4.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class TestType
    {
        /// <summary>* test1
        /// <br/>* test2
    </summary>
        [Newtonsoft.Json.JsonProperty("code", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Code { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties = new System.Collections.Generic.Dictionary<string, object>();

        [Newtonsoft.Json.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties; }
            set { _additionalProperties = value; }
        }

    }
```

As you see the closing `</summary>` tag doesn't start with `///` which breaks the compilation

**Comment by RicoSuter** [comment] 2021-12-14 11:19
Yes, "\n" are not removed anymore which causes this problem...

/cc @lahma

**Comment by kvantetore** [comment] 2021-12-14 11:29
It seems like the issue was introduced in 463d246d0564c1d919503c15dbf0590b11ea0f1a by substituting 
`.Replace("\n", "\n" + string.Join("", Enumerable.Repeat("    ", tabCount)) + "/// ")`
with a call to `AddPrefixToBeginningOfNonEmptyLines()` in [ConversionUtilities.cs line 264.](https://github.com/RicoSuter/NJsonSchema/blob/76afab604e749528104760c170aa83a01b1cbdb2/src/NJsonSchema/ConversionUtilities.cs#L282)

The `AddPrefixToBeginningOfNonEmptyLines()` kind of makes sense for the `| tab` filter, but does not work as intended for the `| csharpdocs` filter.  Imo `///` should be added to empty lines as well as non-empty lines.

**Comment by lahma** [comment] 2021-12-14 18:15
I'll have a look.

**Comment by lahma** [comment] 2021-12-14 18:59
Fixed in https://github.com/RicoSuter/NJsonSchema/pull/1463

**Closed** 2021-12-14 19:47 UTC

**Comment by vadimi** [comment] 2021-12-16 22:46
thanks for fixing the issue!
